# Numpy

In [1]:
import numpy as np

## Numpy Array
mirip list tapi bukan list, kita isi angka semua datanya.

### CRUD: Create Read Update Delete
- Create
    - np.array([1,2,3]) membuat numpoy array dari sebuah list
    - np.zeros(10) membuat numpy array berisi angka 0 dengan ukuran 10
    - np.ones(5) membuat numpy array berisi angka 1 dengan ukuran 5
    - np.empty(7) membuat numpy array berisi "kosong" ukuran 7
    - np.arange(5) membuat numpy array berisi angka urut dari 0,1,2,3,4
        - np.arange(5,10) membuat numpy array berisi angka urut dari 5,6,7,8,9
        - np.arange(10,100,25) membuat numpy array berisi angka urut dari 10,35,80
    - np.random.random(15) membuat numpy array berisi angka random antara 0-1 ukuran 15

In [3]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
a = np.array([[1,2,3], [4,5,6]])
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [7]:
np.zeros(3)

array([0., 0., 0.])

In [186]:
# buat 2d
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [187]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.empty(7)

array([0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 3.1408287e-317])

In [188]:
np.empty((1,3))

array([[0.e+000, 1.e-323, 2.e-323]])

In [16]:
print(np.arange(5))
print(np.arange(5, 10))
print(np.arange(5, 12, 2))

[0 1 2 3 4]
[5 6 7 8 9]
[ 5  7  9 11]


In [190]:
np.arange(5, 11).reshape((2,3))

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [19]:
np.random.random(10)

array([0.2859548 , 0.37626553, 0.90384066, 0.94629998, 0.94538043,
       0.19071768, 0.56295424, 0.28960985, 0.49328426, 0.25405303])

In [192]:
np.random.random(10).reshape((5,2))

array([[0.79988658, 0.53920398],
       [0.87804597, 0.77597085],
       [0.83677492, 0.89089683],
       [0.58276312, 0.64858508],
       [0.97827123, 0.10437256]])

In [23]:
# contoh hasil lempar dadu 6 sisi sebanyak 10 kali
# bisa lihat cara lain menggunakan np.random di https://www.w3schools.com/python/numpy/numpy_random.asp
(np.random.random(10) * 6 + 1).astype(int)

array([5, 2, 5, 1, 5, 6, 6, 3, 6, 4])

In [193]:
# seperti hasil lempar 2 dadu sekaligus, 5 kali
(np.random.random(10) * 6 + 1).astype(int).reshape((5,2))

array([[2, 4],
       [4, 2],
       [5, 1],
       [2, 4],
       [1, 6]])

### Read
anggap arr adalah sebuah numpy array
- arr.shape melihat bentuk numpy array, jumlah kolom dan baris
- arr.size melihat ukuran numpy array, ada berapa angka di dalam
- arr.ndim melihat dimensi sebuah numpy array

In [27]:
arr = np.array([2,5,7,9,0])

print(arr.shape)
print(arr.size)
print(arr.ndim)

(5,)
5
1


In [29]:
arr = np.array([[2,5,7,9,0]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[2 5 7 9 0]]
(1, 5)
5
2


In [30]:
arr = np.array([[2,5,7,9,0], [21,15,17,91,10]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[ 2  5  7  9  0]
 [21 15 17 91 10]]
(2, 5)
10
2


In [31]:
# jumlah angka di setiap baris sebuah numpy array 2 dimensi harus sama,
# kalau tidak dia tidak bisa berlaku sebagai numpy array pada umumnya
# akan ada complain juga dari python nya
arr = np.array([[2,5,7,9], [21,15,17,91,10]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[list([2, 5, 7, 9]) list([21, 15, 17, 91, 10])]
(2,)
2
1


C:\Users\stefa\AppData\Local\Temp\ipykernel_8804\709034576.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[2,5,7,9], [21,15,17,91,10]])


In [34]:
# kalau ada yang kosong, biasanya tetap kita isi dengan "missing value"
arr = np.array([[2,5,7,9, np.NAN], [21,15,17,91,10]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]
(2, 5)
10
2


In [41]:
print(arr)
print()
# cara membaca/ ngambil 1 item dari numpy array, bisa pakai index
print("indexing")
print(arr[0,1], "ambil baris pertama, kolom kedua")

print()
# ambil beberapa item bisa pakai slicing
print("slicing")
print(arr[:, 1:3], "ambil semua baris, kolom kedua sampai kolom ketiga")

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]

indexing
5.0 ambil baris pertama, kolom kedua

slicing
[[ 5.  7.]
 [15. 17.]] ambil semua baris, kolom kedua sampai kolom ketiga


### Update
edit numpy array nya:
- reshape mengubah shape sebuah numpy array
- append menempel 2 numpy array (atau list) jadi satu
- delete hapus item dalam numpy array menggunakan index
- sort sortir item dalam sebuah numpy array dari kecil ke besar

In [43]:
print(arr)
print(arr.shape)

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]
(2, 5)


## Reshape

In [47]:
arr2 = arr.reshape((10,)) # size sebelum dan sesudah reshape harus sama
print(arr2)
print(arr2.shape)

[ 2.  5.  7.  9. nan 21. 15. 17. 91. 10.]
(10,)


In [51]:
arr2 = arr.reshape((1,10)) # 2 dimensi boleh, 3 dimensi boleh, dst...
print(arr2)
print(arr2.shape)

[[ 2.  5.  7.  9. nan 21. 15. 17. 91. 10.]]
(1, 10)


In [48]:
arr2 = arr.reshape((5,2)) # 2 dimensi boleh, 3 dimensi boleh, dst...
print(arr2)
print(arr2.shape)

[[ 2.  5.]
 [ 7.  9.]
 [nan 21.]
 [15. 17.]
 [91. 10.]]
(5, 2)


In [49]:
arr2 = arr.reshape((5,2,1)) # 2 dimensi boleh, 3 dimensi boleh, dst...
print(arr2)
print(arr2.shape)

[[[ 2.]
  [ 5.]]

 [[ 7.]
  [ 9.]]

 [[nan]
  [21.]]

 [[15.]
  [17.]]

 [[91.]
  [10.]]]
(5, 2, 1)


In [52]:
type(arr)

numpy.ndarray

## Append

In [53]:
np.append(arr, [5])

array([ 2.,  5.,  7.,  9., nan, 21., 15., 17., 91., 10.,  5.])

In [54]:
np.append(arr, [5, 10 , 75])

array([ 2.,  5.,  7.,  9., nan, 21., 15., 17., 91., 10.,  5., 10., 75.])

In [68]:
np.append(arr, [[5, 10 , 75], [10, 11, 12]])

array([ 2.,  5.,  7.,  9., nan, 21., 15., 17., 91., 10.,  5., 10., 75.,
       10., 11., 12.])

In [66]:
print([[5, 10 , 75], [10, 11, 12]])

[[5, 10, 75], [10, 11, 12]]


In [72]:
np.append(arr, [[1,2,3,4,5]], axis=0) # pilihan axis 0, append sebagai baris baru

array([[ 2.,  5.,  7.,  9., nan],
       [21., 15., 17., 91., 10.],
       [ 1.,  2.,  3.,  4.,  5.]])

In [73]:
np.append(arr, [[1],[2]], axis=1) # pilihan axis 1, append sebagai baris baru

array([[ 2.,  5.,  7.,  9., nan,  1.],
       [21., 15., 17., 91., 10.,  2.]])

## Delete

In [74]:
print(arr)

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]


In [78]:
# mau hapus angka 9
# index ke 3
np.delete(arr, 3)

# mengubah np array menjadi 1 dimensi

array([ 2.,  5.,  7., nan, 21., 15., 17., 91., 10.])

In [80]:
arr2 = np.array([10,20,30])
print(arr2)

# hapus angka 20, ada di posisi index ke 1
np.delete(arr2, 1)

[10 20 30]


array([10, 30])

In [82]:
## replace
# misal mau menggantikan angka 9 di arr menjadi angka 90
print(arr)

# index angka 9 adalah di baris pertama (index 0), kolom ke 4 (index 3)
arr[0,3] = 90
print(arr)

[[ 2.  5.  7.  9. nan]
 [21. 15. 17. 91. 10.]]
[[ 2.  5.  7. 90. nan]
 [21. 15. 17. 91. 10.]]


## Sort
mengurutkan angka dalam numpy array dari kecil ke besar

In [86]:
print(arr)

[[ 2.  5.  7. 90. nan]
 [21. 15. 17. 91. 10.]]


In [83]:
np.sort(arr)

array([[ 2.,  5.,  7., 90., nan],
       [10., 15., 17., 21., 91.]])

In [84]:
arr2 = np.array([np.NAN, -10,10,5,50])
print(arr2)

print(np.sort(arr2))

[ nan -10.  10.   5.  50.]
[-10.   5.  10.  50.  nan]


In [85]:
np.sort(arr, axis=0)

array([[ 2.,  5.,  7., 90., 10.],
       [21., 15., 17., 91., nan]])

In [87]:
np.sort(arr, axis=1)

array([[ 2.,  5.,  7., 90., nan],
       [10., 15., 17., 21., 91.]])

## Manipulasi Numpy Array
- ubah np array dari 1D jadi 2D
    - newaxis
    - expand_dims
- indexing, slicing, query (dengan kondisi)

## newaxis & expand_dims

In [94]:
arr2 = np.array([9,12,67,-5])
print(arr2)
print(arr2.shape)

[ 9 12 67 -5]
(4,)


In [92]:
a3 = arr2[np.newaxis]
print(a3)
print(a3.shape)

[[ 9 12 67 -5]]
(1, 4)


In [93]:
a3 = arr2[:, np.newaxis]
print(a3)
print(a3.shape)

[[ 9]
 [12]
 [67]
 [-5]]
(4, 1)


In [96]:
a3 = np.expand_dims(arr2, axis=0)
print(a3)
print(a3.shape)

[[ 9 12 67 -5]]
(1, 4)


In [97]:
a3 = np.expand_dims(arr2, axis=1)
print(a3)
print(a3.shape)

[[ 9]
 [12]
 [67]
 [-5]]
(4, 1)


## indexing, slicing, query

In [101]:
arr2 = np.arange(100, 400, 25).reshape((3,4))
print(arr2)

[[100 125 150 175]
 [200 225 250 275]
 [300 325 350 375]]


In [102]:
# indexing, mau ambil angka 250
# baris ke2 (index 1), kolom ke3 (index 2)
print(arr2[1,2])

250


In [103]:
# slicing, mau ambil 250 275 350 375
# 250 ada di baris ke2 (index 1), kolom ke3 (index 2)
# 375 ada di baris ke3 (index 2), kolom ke4 (index 3)
print(arr2[1:3, 2:4])

[[250 275]
 [350 375]]


In [104]:
# 250 ada di baris ke2 (index 1), kolom ke3 (index 2)
# 375 ada di baris terakhir, kolom terakhir
print(arr2[1:, 2:])

[[250 275]
 [350 375]]


In [105]:
# 250 ada di baris ke2 dari terakhir (index -2), kolom ke2 dari terakhir  (index -2)
# 375 ada di baris ke3 (index 2), kolom ke4 (index 3)
print(arr2[-2:3, -2:4])

[[250 275]
 [350 375]]


In [106]:
# 250 ada di baris ke2 dari terakhir (index -2), kolom ke2 dari terakhir  (index -2)
# 375 ada di baris terakhir, kolom terakhir
print(arr2[-2:, -2:])

[[250 275]
 [350 375]]


In [107]:
# query
# kita bisa ambil angka2 tertentu dengan kondisi
# misalkan kondisi angka genap
genap = arr2 % 2 == 0

print(genap)

[[ True False  True False]
 [ True False  True False]
 [ True False  True False]]


In [108]:
print(arr2)

[[100 125 150 175]
 [200 225 250 275]
 [300 325 350 375]]


In [109]:
arr2[genap]

array([100, 150, 200, 250, 300, 350])

In [110]:
arr2[arr2 % 2 == 0]

array([100, 150, 200, 250, 300, 350])

In [111]:
arr2[(arr2 % 2 == 0)]

array([100, 150, 200, 250, 300, 350])

In [112]:
# misalkan kita buat kondisi lagi, untuk angka yang di atas 200
diatas200 = arr2 > 200

print(diatas200)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [113]:
print(genap & diatas200)

[[False False False False]
 [False False  True False]
 [ True False  True False]]


In [114]:
arr2[genap & diatas200]

array([250, 300, 350])

In [121]:
arr2[(arr2 % 2 == 0) & (arr2 > 200)]

array([250, 300, 350])

In [122]:
print(arr2)

[[100 125 150 175]
 [200 225 250 275]
 [300 325 350 375]]


perhatikan kondisi yang dibuat itu khusus untuk array tersebut. buatlah kondisi baru khusus untuk setiap array yang mau di query.

In [123]:
print(arr)

[[ 2.  5.  7. 90. nan]
 [21. 15. 17. 91. 10.]]


In [124]:
# ambil angka genap di arr
arr[arr % 2 == 0]

# akan ada complain saat ketemu nan % 2 --> error

C:\Users\stefa\AppData\Local\Temp\ipykernel_8804\4015600997.py:2: RuntimeWarning: invalid value encountered in remainder
  arr[arr % 2 == 0]


array([ 2., 90., 10.])

In [125]:
a = np.array([[ 2,  5,  7, 90, -3], [21, 15, 17, 91, 10]])
print(a)

[[ 2  5  7 90 -3]
 [21 15 17 91 10]]


In [126]:
# ambil angka genap di a
a[a % 2 == 0]

array([ 2, 90, 10])

## stack, split
- stack menumpuk beberapa numpy array jadi satu
    - vstack, secara vertical (atas ke bawah) 
    - hstack, secara horizontal (kiri ke kanan)
- split memisah satu numpy array menjadi beberapa numpy array
    - vsplit, dipisahnya atas, tengah, bawah, yang penting setiap potong ukuran sama
    - hsplit, dispisahnya kiri, tengah, kanan, yang penting setiap potong ukuran sama

In [128]:
print(a)
print(a.shape)

[[ 2  5  7 90 -3]
 [21 15 17 91 10]]
(2, 5)


In [135]:
b = np.arange(5).reshape((1,5))
print(b)
print(b.shape)

[[0 1 2 3 4]]
(1, 5)


In [136]:
# vstack: untuk numpuk secara vertical, ukuran jumlah kolom harus sama
# disini, a dan b masing masing punya 5 kolom, jadi boleh ditumpuk secara vertical
np.vstack((a, b))

array([[ 2,  5,  7, 90, -3],
       [21, 15, 17, 91, 10],
       [ 0,  1,  2,  3,  4]])

In [137]:
np.vstack((a, b, b, a))

array([[ 2,  5,  7, 90, -3],
       [21, 15, 17, 91, 10],
       [ 0,  1,  2,  3,  4],
       [ 0,  1,  2,  3,  4],
       [ 2,  5,  7, 90, -3],
       [21, 15, 17, 91, 10]])

In [139]:
# hstack: untuk numpuk secara horizontal, ukuran jumlah baris harus sama
b = np.array([[3,4], [5,6]])
print(b)
print(b.shape)

np.hstack((a,b))

[[3 4]
 [5 6]]
(2, 2)


array([[ 2,  5,  7, 90, -3,  3,  4],
       [21, 15, 17, 91, 10,  5,  6]])

In [140]:
np.hstack((a,b,a,b))

array([[ 2,  5,  7, 90, -3,  3,  4,  2,  5,  7, 90, -3,  3,  4],
       [21, 15, 17, 91, 10,  5,  6, 21, 15, 17, 91, 10,  5,  6]])

In [141]:
# vsplit: bagi 1 numpy array ke beberapa numpy array, dipotong atas dan bawah dipisah

print(a)

[[ 2  5  7 90 -3]
 [21 15 17 91 10]]


In [142]:
np.vsplit(a, 2)

[array([[ 2,  5,  7, 90, -3]]), array([[21, 15, 17, 91, 10]])]

In [143]:
hasil = np.vsplit(a, 2)

In [145]:
print(hasil)
print(type(hasil))

[array([[ 2,  5,  7, 90, -3]]), array([[21, 15, 17, 91, 10]])]
<class 'list'>


In [146]:
a1, a2 = np.vsplit(a, 2)
print(a1, type(a1))

[[ 2  5  7 90 -3]] <class 'numpy.ndarray'>


In [147]:
print(a2, type(a2))

[[21 15 17 91 10]] <class 'numpy.ndarray'>


In [148]:
a1, a2 = hasil
print(a1, type(a1))
print(a2, type(a2))

[[ 2  5  7 90 -3]] <class 'numpy.ndarray'>
[[21 15 17 91 10]] <class 'numpy.ndarray'>


In [149]:
print(hasil[0], type(hasil[0]))

[[ 2  5  7 90 -3]] <class 'numpy.ndarray'>


In [150]:
# vsplit, contah lain
b = np.arange(12).reshape((3, 4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [153]:
np.vsplit(b,3) # menjadi 1 list isi 3 numpy array

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

```python
np.vsplit(b,2)
```
akan error karena tidak bisa dibagi menjadi 2 np array yang sama ukurannya

In [154]:
# hsplit, memisah np array dari kiri dan kana
# misalnya b dibagi 2
np.hsplit(b, 2) # dapat 1 list isi 2 numpy array

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [155]:
# misalnya b dibagi 4
np.hsplit(b, 4) # dapat 1 list isi 4 numpy array

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

## copy dan view
- copy membuat duplikat numpy array
    - view (by reference)
    - copy (by value) "deep copy"

In [157]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [158]:
b_copy = b.copy()

In [159]:
b_copy[0,1] = 100

print(b_copy)

[[  0 100   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [160]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


mengubah array hasil copy, tidak merubah array awal kita

In [161]:
# kalau view, kena reference
b_view = b.view()

b_view[0,2] = 200

print(b_view)

[[  0   1 200   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [162]:
print(b)

[[  0   1 200   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [163]:
b[1,0] = 40

In [164]:
print(b)

[[  0   1 200   3]
 [ 40   5   6   7]
 [  8   9  10  11]]


In [165]:
print(b_view)

[[  0   1 200   3]
 [ 40   5   6   7]
 [  8   9  10  11]]


b dan b_view adalah array yang sama dengan nama berbeda

In [166]:
print(b_copy)

[[  0 100   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


b_copy adalah array yang berbeda, dengan nama yang berbeda juga

# Basic Array Operation
memanipulasi angka dalam numpy array menggunakan operator matematik dan angka

In [168]:
# kalau list tidak bisa
nilai = [60,78,99,43]

# nilainya mau kita tambahkan 1 poin semua
nilai + [1,1,1,1]

[60, 78, 99, 43, 1, 1, 1, 1]

In [169]:
nilai_arr = np.array(nilai)

nilai_arr + 1

array([ 61,  79, 100,  44])

In [171]:
nilai_arr + [10,10,1,10]

array([ 70,  88, 100,  53])

In [172]:
np.array([60,78,99,43]) + [10,10,1,10]

array([ 70,  88, 100,  53])

numpy array bisa kita edit isinya secara matematik menggunakan list angka lain (ukuran sama), atau 1 angka lain. bisa menggunakan operator matematika pada umunya, \+ \- \/ \* \% \** dan lainnya

In [174]:
np.arange(5) + 5 * 3 / 2

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [177]:
np.arange(5) + np.ones(5) * 8

array([ 8.,  9., 10., 11., 12.])

In [178]:
np.arange(5) % 2

array([0, 1, 0, 1, 0], dtype=int32)

## max, min, sum, mean
selain operator matematik biasa, ada juga fungsi bawaan numpy untuk mencari max, min, sum, mean, dan lainnya

In [179]:
print(a)

[[ 2  5  7 90 -3]
 [21 15 17 91 10]]


In [180]:
# max
print(a.max())

91


In [181]:
# cari per axis
print(a.max(axis=0)) # bandingin baris dengan baris lainnya, cari angka max

[21 15 17 91 10]


In [182]:
print(a.max(axis=1)) # bandingin kolom dengan kolom lainnya, cari angka max

[90 91]


In [183]:
# min
print(a.min())
print(a.min(axis=0))
print(a.min(axis=1))

-3
[ 2  5  7 90 -3]
[-3 10]


In [184]:
# sum, dijumlah
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

255
[ 23  20  24 181   7]
[101 154]


In [185]:
# mean, rata-rata
print(a.mean())
print(a.mean(axis=0))
print(a.mean(axis=1))

25.5
[11.5 10.  12.  90.5  3.5]
[20.2 30.8]


# Matrices
Apa itu matrix? Itu adalah nama yang diberikan untuk sebuah numpy array 2 dimensi yang punya jumlah kolom sama setiap barisnya, dan setiap item adalah sebuah angka.

matrix yang punya 1 kolom saja namanya *vector*, tapi untuk membuat lebih simpel kita panggil saja semuanya sebagai matrix

In [198]:
print(np.array([[-2,5,6],[5,2,7]])) # contoh matrix

[[-2  5  6]
 [ 5  2  7]]


In [197]:
print([[-2,5,6],[5,2,7]]) # bisa dilihat python sudah bedain visual hasil print list biasa dibanding matrix

[[-2, 5, 6], [5, 2, 7]]


# Dot Product
teknik perkalian spesial antara dua matrix

untuk melihat secara visual teknik dot product bisa ke https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [199]:
# perkalian antara 2 numpy array itu mengkalikan angka yang ada di posisi sama dari np array a dan b

np.array([1,2]) * np.array([5,6])

# 1 * 5, 2 * 6
# kita akan dapat hasil perkaliannya jadi numpy array [5, 12]

array([ 5, 12])

In [200]:
a = np.arange(1,7).reshape((2,3))
b = np.arange(7,13).reshape((3,2))

a.dot(b)

array([[ 58,  64],
       [139, 154]])

In [202]:
# contoh pemakaian
penjualan = np.array([[13,9,7,15],
                      [8,7,4,6],
                      [6,4,0,3]
                     ])
harga = np.array([3,4,2])

total_penjualan_per_hari = harga.dot(penjualan)
print(total_penjualan_per_hari)

print("grand total", total_penjualan_per_hari.sum())

[83 63 37 75]
grand total 258


# transpose vs reshape

In [203]:
print(penjualan)

[[13  9  7 15]
 [ 8  7  4  6]
 [ 6  4  0  3]]


In [204]:
print(penjualan.T)

[[13  8  6]
 [ 9  7  4]
 [ 7  4  0]
 [15  6  3]]


In [205]:
print(penjualan.T.T)

[[13  9  7 15]
 [ 8  7  4  6]
 [ 6  4  0  3]]


In [208]:
penjualan.transpose() # cara lain transpose, selain .T

array([[13,  8,  6],
       [ 9,  7,  4],
       [ 7,  4,  0],
       [15,  6,  3]])

In [206]:
# kalau reshape, datanya kecampur
print(penjualan.reshape((4,3)))

[[13  9  7]
 [15  8  7]
 [ 4  6  6]
 [ 4  0  3]]


In [209]:
print(penjualan.reshape((4,3)).reshape((3,4)))

[[13  9  7 15]
 [ 8  7  4  6]
 [ 6  4  0  3]]


transpose memastikan teman sebaris menjadi teman sekolom

# N-Dimensional Array
numpy array bisa punya dimensi bebas, 1,2,3,4,...

In [211]:
np.arange(60).reshape((4,5,3)) # 3d, 4 bagian, masing-masing 5 baris, setiap baris ada 3 kolom

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]],

       [[45, 46, 47],
        [48, 49, 50],
        [51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [212]:
np.arange(60).reshape((2,5,3,2)) # 2 bagian, masing masing punya 5 bagian, tiap bagian ada 3 baris, tiap baris punya 2 kolom 

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]],

        [[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]]],


       [[[30, 31],
         [32, 33],
         [34, 35]],

        [[36, 37],
         [38, 39],
         [40, 41]],

        [[42, 43],
         [44, 45],
         [46, 47]],

        [[48, 49],
         [50, 51],
         [52, 53]],

        [[54, 55],
         [56, 57],
         [58, 59]]]])

In [213]:
# biasanya kita akan bekerja dengan np array 2 dimensi
np.arange(20).reshape((4,5)) 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [214]:
# atau 1 dimensi
np.arange(5).reshape((5,)) 

array([0, 1, 2, 3, 4])

# Flatten
teknik untuk mengubah numpy array menjadi 1 dimensi
- flatten (by value, mirip copy)
- ravel (by reference, mirip view)

In [220]:
arr3d = np.arange(30).reshape((2,5,3))
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [221]:
# buat jadi 1d
arr3d_flat = arr3d.flatten()
arr3d_ravel = arr3d.ravel()

print(arr3d_flat)
print(arr3d_ravel)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [222]:
# kalau yang di ravel berubah, aslinya ikut berubah juga
arr3d_ravel[0] = 500

In [223]:
print(arr3d_ravel)

[500   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]


In [224]:
print(arr3d) # perhatikan walaupun asli 3d, yg ravel 1d, isinya masih nyambung

[[[500   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]]

 [[ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]]


In [225]:
arr3d_flat[0] = 150
print(arr3d_flat)

[150   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]


In [226]:
print(arr3d)

[[[500   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]]

 [[ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]]]


### latihan
buat sebuah numpy array 2 dimensi ukuran 5 * 6 (5 baris 6 kolom):
- gunakan np.array, np.zeros, np.arange - isi angka bebas
- coba menggunakan indexing dan slicing untuk mengambil 1 angka dan bbrp angka dari numpy array yang sudah dibuat
    - misal ambil angka di baris pertama, kolom ke3
    - misal ambil angka di baris 2-4, kolom terakhir
- coba dot product np.array([5,4,6,7,8]) dengan array yang sudah dibuat

# paling sering dipakai
- np.array, np.arange, np.ones
- np.random.random
- shape
- reshape
- \+ \- \* \\ dengan angka atau numpy array lain
- aggregate (sum, min, max, mean)
- indexing dan slicing
- transpose

In [231]:
# buat np array isi angka 100 semua
(np.ones(10) * 100).reshape((2,5))

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

In [228]:
np.zeros(10) + 100

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])